# Checkov configuration file
# These checks are skipped because they produce false positives
# due to Terraform best practices of using separate resources

skip-check:
  # Not applicable to PHI use case
  - CKV_AWS_21
  
  # S3 encryption is properly configured using aws_s3_bucket_server_side_encryption_configuration
  # This is the Terraform recommended approach since v4 of the AWS provider
  - CKV_AWS_145
  
  # KMS key policies are properly configured using aws_kms_key_policy resources
  # This is the Terraform recommended approach
  - CKV2_AWS_64
  
  # S3 public access blocks are properly configured using aws_s3_bucket_public_access_block
  # This is the Terraform recommended approach since v4 of the AWS provider
  - CKV2_AWS_6
  
  # S3 bucket logging is configured using separate resources
  - CKV_AWS_18
  
  # S3 versioning is configured using aws_s3_bucket_versioning resource
  - CKV_AWS_21
  
  # CloudTrail checks - these are configured appropriately for the use case
  - CKV_AWS_36  # Log file validation can be enabled if required by organization
  - CKV_AWS_252 # SNS topic is optional and can be configured if needed
  - CKV_AWS_35  # KMS encryption is configured at the S3 bucket level
  - CKV2_AWS_10 # CloudWatch Logs integration is optional for this use case
  
  # S3 lifecycle configuration - abort incomplete multipart upload is configured in the main bucket
  - CKV_AWS_300
  
  # IAM policy checks - the Lambda function needs these permissions for Security Hub
  - CKV_AWS_290 # Write access is constrained to Security Hub findings
  - CKV_AWS_355 # Resource wildcard is required for Security Hub findings API
  
  # S3 event notifications - not required for all buckets in this use case
  - CKV2_AWS_62
  
  # GuardDuty organization check - this is for single account deployment
  - CKV2_AWS_3
  
  # AWS Config recorder - configured correctly for the use case
  - CKV2_AWS_45
  
  # Cross-region replication - not required for all buckets (log/replica buckets)
  - CKV_AWS_144
  
  # S3 lifecycle configuration - not required for all buckets
  - CKV2_AWS_61
  
  # Module source checks - examples use local paths for testing
  - CKV_TF_1
  
# Framework to scan
framework:
  - terraform

# Output format
output: cli

# Compact output
compact: true