# Checkov configuration file
# These checks are skipped because they produce false positives
# due to Terraform best practices of using separate resources

skip-check:
  # Not applicable to PHI use case
  - CKV_AWS_21
  
  # S3 encryption is properly configured using aws_s3_bucket_server_side_encryption_configuration
  # This is the Terraform recommended approach since v4 of the AWS provider
  - CKV_AWS_145
  
  # KMS key policies are properly configured using aws_kms_key_policy resources
  # This is the Terraform recommended approach
  - CKV2_AWS_64
  
  # S3 public access blocks are properly configured using aws_s3_bucket_public_access_block
  # This is the Terraform recommended approach since v4 of the AWS provider
  - CKV2_AWS_6
  
  # S3 bucket logging is configured using separate resources
  - CKV_AWS_18
  
  # S3 versioning is configured using aws_s3_bucket_versioning resource
  - CKV_AWS_21
  
# Framework to scan
framework:
  - terraform

# Output format
output: cli

# Compact output
compact: true