# tfsec configuration for PHI S3 bucket module
# Focused on HIPAA compliance and security best practices

severity_overrides:
  # S3 specific overrides for PHI compliance
  aws-s3-enable-bucket-encryption: ERROR
  aws-s3-enable-bucket-logging: ERROR
  aws-s3-enable-versioning: ERROR
  aws-s3-encryption-customer-key: ERROR
  aws-s3-no-public-buckets: ERROR
  aws-s3-block-public-acls: ERROR
  aws-s3-block-public-policy: ERROR
  aws-s3-ignore-public-acls: ERROR
  aws-s3-no-public-access-with-acl: ERROR
  aws-s3-specify-public-access-block: ERROR
  
  # KMS encryption requirements
  aws-kms-auto-rotate-keys: ERROR
  
  # General security
  aws-iam-no-policy-wildcards: WARNING
  general-secrets-no-plaintext-exposure: ERROR

# Exclude certain paths from scanning
exclude_paths:
  - .terraform/
  - "**/*.tfvars"
  - "**/terraform.tfvars.example"

# Custom checks for PHI compliance
custom_checks:
  - code: PHI-001
    description: S3 buckets containing PHI must have encryption enabled
    severity: ERROR
    resource_types:
      - aws_s3_bucket
    match_attributes:
      - server_side_encryption_configuration
    
  - code: PHI-002
    description: S3 buckets containing PHI must have versioning enabled
    severity: ERROR
    resource_types:
      - aws_s3_bucket_versioning
    match_attributes:
      - versioning_configuration.status
    
  - code: PHI-003
    description: S3 buckets containing PHI must have access logging enabled
    severity: ERROR
    resource_types:
      - aws_s3_bucket_logging
    
  - code: PHI-004
    description: KMS keys for PHI must have automatic rotation enabled
    severity: ERROR
    resource_types:
      - aws_kms_key
    match_attributes:
      - enable_key_rotation

# Include paths to scan
include_paths:
  - modules/
  - examples/
  - tests/

# Minimum severity to report
minimum_severity: INFO

# Output format
format: json