---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  comments:
    min-spaces-from-content: 2
  
  brackets:
    max-spaces-inside: 1
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  empty-lines:
    max: 2
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  
  key-duplicates: enable
  
  new-line-at-end-of-file: enable
  
  trailing-spaces: enable

ignore: |
  .terraform/
  .git/
  vendor/