name: Terraform CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.6.5"
  TFLINT_VERSION: "0.49.0"
  TFSEC_VERSION: "1.28.4"
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Format Check
        id: fmt
        run: |
          terraform fmt -check -recursive -diff
        continue-on-error: true

      - name: Cache Terraform modules
        uses: actions/cache@v3
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: |
          # Initialize root module
          echo "Initializing root module"
          terraform init -backend=false
          
          # Initialize submodules
          for dir in modules/*/; do
            echo "Initializing $dir"
            terraform -chdir="$dir" init -backend=false
          done

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v${{ env.TFLINT_VERSION }}

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive --minimum-failure-severity=error

      - name: Terraform Validate
        run: |
          # Validate root module
          echo "Validating root module"
          terraform validate
          
          # Validate submodules
          for dir in modules/*/; do
            echo "Validating $dir"
            terraform -chdir="$dir" validate
          done

      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`
            Format check: ${{ steps.fmt.outcome }}
            \`\`\`
            
            </details>
            
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          version: v${{ env.TFSEC_VERSION }}
          soft_fail: false
          config_file: .tfsec.yml
          github_token: ${{ github.token }}

      - name: Upload tfsec results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfsec-results
          path: tfsec-results.json

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Detect secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./modules/s3-phi-bucket
          output-file: README.md
          output-method: inject
          git-push: "true"

  test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: [validate, security]
    
    strategy:
      matrix:
        test_dir:
          - tests/basic_test.tf
          - tests/compliance_test.tf
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Run Terraform Test
        run: |
          terraform test -test-directory=${{ matrix.test_dir }}
        continue-on-error: true

  cost-estimation:
    name: Cost Estimation
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/setup-infracost@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        run: |
          infracost breakdown --path=examples/basic \
            --format=json \
            --out-file=/tmp/infracost-base.json

      - name: Generate Infracost Report
        run: |
          infracost output --path=/tmp/infracost-base.json --format=github-comment

      - name: Post Infracost comment
        if: github.event_name == 'pull_request'
        uses: infracost/infracost-gh-action@v1
        with:
          path: examples/basic
          github_token: ${{ secrets.GITHUB_TOKEN }}

  compliance-check:
    name: Compliance Verification
    runs-on: ubuntu-latest
    needs: [validate, security]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install compliance tools
        run: |
          pip install checkov
          pip install terrascan

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: false
          skip_check: CKV_AWS_21  # Skip checks not applicable to PHI use case

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: checkov-results.sarif

      - name: Run Terrascan
        run: |
          terrascan scan -i terraform -d modules/ --config-path .terrascan.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [validate, security, test, compliance-check]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install semantic-release
        run: |
          npm install -g semantic-release
          npm install -g @semantic-release/git
          npm install -g @semantic-release/changelog

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release